// this file is automatically generated.
// if you modify it by hand, your changes will probably be lost.


import CWinRT;
import CWindowsSdk;
@_spi(IUnknown) import WinRT;
import WindowsSdk;
import WindowsApp;

extension Microsoft.Graphics.Canvas.Brushes {
// type: Microsoft.Graphics.Canvas.Brushes.ICanvasBrush
// interface type
open class ICanvasBrush
    :
    WinRT.IInspectable
{
    override public class var IID : CWinRT.IID { CWinRT.IID(Data1: 0xf5d58591, Data2: 0xc803, Data3 : 0x41b4, Data4 : (0x87, 0x8e, 0x79, 0xd9, 0x2a, 0xb1, 0x32, 0x95)) }
// method not needed: get_Opacity
// method not needed: put_Opacity
// method not needed: get_Transform
// method not needed: put_Transform
// method not needed: get_Device
} // ICanvasBrush


}
