// this file is automatically generated.
// if you modify it by hand, your changes will probably be lost.

public struct Microsoft { }
extension Microsoft { public struct UI { } }
extension Microsoft.UI { public struct Composition { } }
extension Microsoft.UI { public struct Dispatching { } }
extension Microsoft.UI { public struct Xaml { } }
extension Microsoft.UI.Xaml { public struct Controls { } }
extension Microsoft.UI.Xaml.Controls { public struct Primitives { } }
extension Microsoft.UI.Xaml { public struct Documents { } }
extension Microsoft.UI.Xaml { public struct Media { } }
extension Microsoft { public struct Windows { } }
extension Microsoft.Windows { public struct System { } }
extension Microsoft.Windows.System { public struct Power { } }
public struct Windows { }
extension Windows { public struct Data { } }
extension Windows.Data { public struct Xml { } }
extension Windows.Data.Xml { public struct Dom { } }
extension Windows { public struct Foundation { } }
extension Windows.Foundation { public struct Collections { } }
extension Windows { public struct Security { } }
extension Windows.Security { public struct Cryptography { } }
extension Windows { public struct Storage { } }
extension Windows.Storage { public struct Streams { } }
extension Windows { public struct System { } }
extension Windows.System { public struct Profile { } }
extension Windows { public struct UI { } }
extension Windows.UI { public struct Core { } }
extension Windows.UI { public struct Notifications { } }
extension Windows.UI { public struct Text { } }
extension Windows { public struct Web { } }
extension Windows.Web { public struct Http { } }
extension Windows.Web.Http { public struct Filters { } }
