// this file is automatically generated.
// if you modify it by hand, your changes will probably be lost.


import CWinRT;

extension Windows.UI.Xaml.Controls.Primitives {
// type: Windows.UI.Xaml.Controls.Primitives.ComponentResourceLocation
// enum type
public typealias ComponentResourceLocation = _q_CWindows_CUI_CXaml_CControls_CPrimitives_CComponentResourceLocation;

}
extension WinRT.Windows.UI.Xaml.Controls.Primitives.ComponentResourceLocation {
    public static var Application : Self {
        get {
            return _q_CWindows_CUI_CXaml_CControls_CPrimitives_CComponentResourceLocation_Application;
        }
    }
    public static var Nested : Self {
        get {
            return _q_CWindows_CUI_CXaml_CControls_CPrimitives_CComponentResourceLocation_Nested;
        }
    }
}
