// this file is automatically generated.
// if you modify it by hand, your changes will probably be lost.


import CWinRT;

extension Windows.Graphics.Imaging {
// type: Windows.Graphics.Imaging.BitmapSize
// struct type
public typealias BitmapSize = _q_CWindows_CGraphics_CImaging_CBitmapSize;

}
